### ISSUE TITLE
Queries to explorer.darkcoin.io return 403 HTTP error

### ISSUE THREAD

**Issue by c0ding** [c0ding/darkcoin-api#1]
```
======================================================================
ERROR: test_addressbalance (__main__.darkcointestsuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/darkcoin-api/tests/darkcoin_tests.py", line 37, in test_addressbalance
    darkcoin.addressbalance('n194KCwPQJjti53z9gN6wh9wUChfVePEab')
  File "/usr/local/lib/python2.7/dist-packages/darkcoin/darkcoin_api.py", line 66, in addressbalance
    d = urllib2.urlopen(blockexplorer('addressbalance') + '/' + str(PARAMETER))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```
Will have to implement Browser headers as was done for ```http://api.cryptocoincharts.info/```

**Comment by c0ding** [comment]
```
Building in workspace /var/lib/jenkins/workspace/darkcoin-api

Deleting project workspace... done

Cloning the remote Git repository
Cloning repository https://github.com/c0ding/darkcoin-api.git
 > git init /var/lib/jenkins/workspace/darkcoin-api # timeout=10
Fetching upstream changes from https://github.com/c0ding/darkcoin-api.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git8589863606988940396.credentials # timeout=10
 > git fetch --tags --progress https://github.com/c0ding/darkcoin-api.git +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/c0ding/darkcoin-api.git # timeout=10
 > git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/c0ding/darkcoin-api.git # timeout=10
Fetching upstream changes from https://github.com/c0ding/darkcoin-api.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7733905889603810471.credentials # timeout=10
 > git fetch --tags --progress https://github.com/c0ding/darkcoin-api.git +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision e976f41046fa2700c6f792cb1714e7388634d73e (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e976f41046fa2700c6f792cb1714e7388634d73e
 > git rev-list e976f41046fa2700c6f792cb1714e7388634d73e # timeout=10
[darkcoin-api] $ /bin/sh -xe /tmp/hudson8608063649450415226.sh
+ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/darkcoin
copying darkcoin/darkcoin_utils.py -> build/lib.linux-x86_64-2.7/darkcoin
copying darkcoin/darkcoin_api.py -> build/lib.linux-x86_64-2.7/darkcoin
copying darkcoin/__init__.py -> build/lib.linux-x86_64-2.7/darkcoin
running install_lib
copying build/lib.linux-x86_64-2.7/darkcoin/darkcoin_utils.py -> /usr/local/lib/python2.7/dist-packages/darkcoin
copying build/lib.linux-x86_64-2.7/darkcoin/darkcoin_api.py -> /usr/local/lib/python2.7/dist-packages/darkcoin
copying build/lib.linux-x86_64-2.7/darkcoin/__init__.py -> /usr/local/lib/python2.7/dist-packages/darkcoin
byte-compiling /usr/local/lib/python2.7/dist-packages/darkcoin/darkcoin_utils.py to darkcoin_utils.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/darkcoin/darkcoin_api.py to darkcoin_api.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/darkcoin/__init__.py to __init__.pyc
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/darkcoin-0.2.egg-info
Writing /usr/local/lib/python2.7/dist-packages/darkcoin-0.2.egg-info
+ python /var/lib/jenkins/workspace/darkcoin-api/tests/darkcoin_tests.py
.................
----------------------------------------------------------------------
Ran 17 tests in 5.352s

OK
[darkcoin-api] $ /bin/sh -xe /tmp/hudson784312301914491284.sh
+ prospector --zero-exit --output-format pylint
Finished: SUCCESS
```
Issue was with ```explorer.darkcoin.io```, not with the project.
